In [1]:
import torch

In [2]:
cpu_tensor = torch.zeros(2,3)
device = torch.device("cuda:0")
gpu_tensor = cpu_tensor.to(device)
print(gpu_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')


In [3]:
X = torch.Tensor(2,3)
X

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
X = torch.tensor([[1,2,3],[4,5,6]])
X

tensor([[1, 2, 3],
        [4, 5, 6]])

In [5]:
x_tensor = torch.tensor(data=[2.0,3.0], requires_grad=True)
x_tensor

tensor([2., 3.], requires_grad=True)

In [6]:
x = torch.tensor(data=[2.,3.], requires_grad=True)
y = x**2
z = 2*y + 3

target = torch.tensor([3.0,4.0])
loss = torch.sum(torch.abs(z-target))
loss.backward()

print(x.grad, y.grad,z.grad)

tensor([ 8., 12.]) None None


In [7]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init


In [8]:
num_data = 1000
num_epoch = 500

x = init.uniform_(torch.Tensor(num_data,1),-10,10)
noise = init.normal_(torch.FloatTensor(num_data,1),std=1)
y = 2*x+3
y_noise = 2*(x+noise) + 3

In [9]:
model = nn.Linear(1,1)
loss_func = nn.L1Loss()

optimizer = optim.SGD(model.parameters(),lr=0.01)

In [11]:
label = y_noise
for i in range(num_epoch):
    optimizer.zero_grad()
    output = model(x)
    
    loss = loss_func(output,label)
    loss.backward()
    optimizer.step()
    
    if i % 10 == 0:
        print(loss.data)

param_list = list(model.parameters())
print(param_list[0].item(), param_list[1].item())

tensor(10.7673)
tensor(8.3857)
tensor(6.1623)
tensor(4.3416)
tensor(3.3877)
tensor(3.0499)
tensor(2.9231)
tensor(2.8352)
tensor(2.7612)
tensor(2.6935)
tensor(2.6291)
tensor(2.5676)
tensor(2.5086)
tensor(2.4526)
tensor(2.4000)
tensor(2.3504)
tensor(2.3038)
tensor(2.2583)
tensor(2.2143)
tensor(2.1719)
tensor(2.1313)
tensor(2.0929)
tensor(2.0573)
tensor(2.0248)
tensor(1.9946)
tensor(1.9661)
tensor(1.9396)
tensor(1.9152)
tensor(1.8914)
tensor(1.8679)
tensor(1.8451)
tensor(1.8242)
tensor(1.8043)
tensor(1.7859)
tensor(1.7691)
tensor(1.7537)
tensor(1.7390)
tensor(1.7255)
tensor(1.7133)
tensor(1.7021)
tensor(1.6919)
tensor(1.6828)
tensor(1.6742)
tensor(1.6661)
tensor(1.6586)
tensor(1.6514)
tensor(1.6449)
tensor(1.6387)
tensor(1.6336)
tensor(1.6291)
1.9809855222702026 2.504599094390869
